Neos:
  Neos:
    fusion:
      autoInclude:
        Carbon.Form: true

Carbon:
  IncludeAssets:
    Packages:
      Carbon.Form:
        Package: Carbon.Form
        # ConditionPrototype: 'GesagtGetan.Form:IncludeCase'
        General:
          Head:
            - Main.js[defer]
